### ISSUE TITLE
Thats going to be my favorite wm, thank you for your work

### ISSUE THREAD

**Issue by TymekBrunka** [altermo/nxwm#3]
thank you for making this amazing window manager, it is fun to use and because it basicly tries to cover nvim windows, winshift works and tabs can be used as workspaces.

Very hackable and extensible even with nvim plugins, thank you.

Are you Planning to make any plugins for this wm like tabline with clock, date etc?

Hope your work will be apreceated (howether you write those 2 words).
Nxwm my new beloved.

**Comment by altermo** [comment]
Thanks for the kind words.
No, I'm not planning to add such things.

**Comment by TymekBrunka** [comment]
and if talking about issues:
- floating windows tile,
- maps option in setup function doesnt seem to work (as an alternative i use vim.keymap.set because if other wm uses those keybinds, then terminal emulator cant catch them).

**Comment by TymekBrunka** [comment]
and how do i make windows move from i tab to another?

**Comment by altermo** [comment]
The same way you would move one buffer from one tab to another.
Here's an example of a function for doing that:
```lua
local function tabbufmove(num)
  local buf=vim.fn.bufnr()
  local win=vim.api.nvim_get_current_win()
  vim.cmd.tabnext(num)
  vim.cmd.sbuf{buf,mods={vertical=true}}
  vim.api.nvim_win_close(win,true)
end
```

**Comment by TymekBrunka** [comment]
idk why but this works better tbh (also thank you)

```lua
local function tabbufmove(num)
  local buf=vim.fn.bufnr()
  local win=vim.api.nvim_get_current_win()
  vim.cmd.tabnext(num)
  vim.cmd("vs")
  vim.cmd("buffer "..buf")
  vim.api.nvim_win_close(win,true)
end
```
